CREATE TABLE IF NOT EXISTS bulkreply (
		  idbulkreply INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		  request varchar(255),
		  type int,
		  ttl int,
		  len int,
		  data varchar(255),
		  ip_src varchar(16),
		  ip_dst varchar(16),
		  udp_src int,
		  udp_dst int,
		  tstamp timestamp
);

CREATE TABLE IF NOT EXISTS config (
  idconfig INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  configname varchar(16),
  configval varchar(16)
);

INSERT INTO config (idconfig, configname, configval)
values(1, 'localdns', '192.168.0.1' );
